### ISSUE TITLE
Issueテンプレートの作成

### ISSUE THREAD

**Issue by UramnOIL** [famima65536/Defragmentation-of-PocketMine-Information#2]
[リポジトリ用に Issue テンプレートを設定する](https://docs.github.com/ja/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

Issueテンプレートがあると気軽に参加しやすくなると思います:thumbsup:

**Comment by famima65536** [comment]
追加します！提案ありがとうございます。
