### ISSUE TITLE
画像用のディレクトリ

### ISSUE THREAD

**Issue by UramnOIL** [famima65536/Defragmentation-of-PocketMine-Information#8]
画像を管理するためのディレクトリが欲しいです。

ディレクトリの配置方法としては
- `/images/`以下にコンテンツに対応したディレクトリを作る。
- コンテンツが置かれているディレクトリにそれぞれ`images/`を作る。
の二つのどちらかが良いと考えています。

**Comment by famima65536** [comment]
#9 に飛ばしました
